### ISSUE TITLE
Ajax by default looks wrong

### ISSUE THREAD

**Issue by manelclos** [bashu/django-fancybox#7]
I tried to use it and I got text in fancybox instead of the image, this is because the code uses type: 'ajax' by default:

```
    $("a[class*=fancybox]").fancybox({type: 'ajax'});
```

Removing it makes it work.

```
    $("a[class*=fancybox]").fancybox();
```

There should be some way to specify ajax and other options, and should not be default.

**Comment by bashu** [comment]
@manelclos see updated example
